   name: happyAPI
   main: de.michaelzinn.minecraft.happyapi.HappyAPI
   version: 0.0

   commands:
      h:
         description: Use a player's service. You may abbreviate the player name.
         usage: /<command> [player] parameters (ask [player])
         permission: <plugin name>.use
         permission-message: You don't have <permission>

      hregister:
         description: Register your own API.
         usage: /<command> URL or IP.
         permission: <plugin name>.register
         permission-message: You don't have <permission>


