name: PlayerServices
description: A plugin that allows players to link chat services to their usernames.
main: de.michaelzinn.playerservices.PlayerServices
version: '1.0.0-alpha'
api-version: '1.20'

commands:
  ps:
    description: Player services administration through subcommands, e.g. register/unregister. Specifying no subcommand outputs a help text.
    usage: /<command> [register|unregister|help] [URL|IP address]
    permission: playerservices.admin
    permission-message: You do not have permission to administrate player services.
  p:
    aliases: h
    description: Use a player's service in privacy mode (only sends player name, id, command and parameters to the service).
    usage: /<command> [player] parameters
    permission: playerservices.user
    permission-message: You do not have permission to use player services.
  s:
    description: Use a player's service service in sharing mode (sends data of privacy mode plus player coordinates, dimension, yaw and pitch).
    usage: /<command> [player] parameters
    permission: playerservices.user
    permission-message: You do not have permission to use player services.
