name: PlayerServices
description: A plugin that allows players to link chat services to their usernames.
main: de.michaelzinn.playerservices.PlayerServices
version: '1.0.0-alpha'
api-version: '1.20'

commands:
  ps:
    description: Register/unregister your player service through subcommands.
    usage: /<command> register <URL or IP address> | /<command> unregister
    permission: playerservices.register
    permission-message: You do not have permission to register or unregister your player service.
  p:
    description: Use a player service in privacy mode (only sends player name, id, command and parameters to the service).
    usage: /<command> <player> parameters
    permission: playerservices.use
    permission-message: You do not have permission to use player services.
  s:
    aliases: h
    description: Use a player service service in sharing mode (sends data of privacy mode plus player coordinates, dimension, yaw and pitch).
    usage: /<command> <player> parameters
    permission: playerservices.use
    permission-message: You do not have permission to use player services.
